# Generated by Django 3.0.5 on 2020-09-15 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coffeemachinetype',
            name='display_name',
        ),
        migrations.RemoveField(
            model_name='coffeepodflavor',
            name='display_name',
        ),
        migrations.RemoveField(
            model_name='coffeepodtype',
            name='display_name',
        ),
    ]
