# Generated by Django 3.0.5 on 2020-09-14 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeemachine',
            name='water_line_compatible',
            field=models.BooleanField(default=False),
        ),
    ]
