# Generated by Django 3.0.5 on 2020-09-14 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200914_2114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coffeemachine',
            old_name='prod_type',
            new_name='product_type',
        ),
    ]
